language: go

go:
  - 1.12.x

cache:
  directories:
    - data

before_install:
  - go get -v ./...
  - nvm install 12.6.0

script:
  - go run main.go
  - cd web
  - npm i
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: web/www
  target_branch: gh-pages
  on:
    branch: master
