# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/Nicell/where-to-live
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: cd web && npm i
      - run: cd web && npm run build
      - persist_to_workspace:
          root: web
          paths: www
  deploy:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - attach_workspace:
          at: web
      - run: gh-pages --dist web/www

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
