# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/Nicell/where-to-live
    steps:
      - checkout
      - restore_cache:
          keys:
            - data-v1
            - node-v1-{{ .Branch }}-{{ checksum "web/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: go get -v -t -d ./...
      - run: go run main.go
      - save_cache:
          key: data-v1
          paths:
            - data
      - run: cd web && npm i
      - save_cache:
          paths:
            - web/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "web/package-lock.json" }}
      - run: cd web && npm run build
      - persist_to_workspace:
          root: web
          paths: www
  deploy:
    docker:
      - image: node:12.6
    steps:
      - checkout
      - attach_workspace:
          at: web
      - run: npm i -g gh-pages
      - add_ssh_keys:
          fingerprints:
            - "1d:89:d9:d5:87:68:30:6a:42:5e:43:06:b8:d6:ee:41"
      - run: gh-pages --message "[ci skip] CircleCI Deployment" --dist web/www/where-to-live

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
